apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ey054vp4c-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ey054vp4c-java-quarkus-gitops