apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ey054vp4c-java-quarkus
  janus-idp.io/tekton: ey054vp4c-java-quarkus
  backstage.io/kubernetes-id: ey054vp4c-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ey054vp4c-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
